// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbNm_Na9Bd9w-P5qYbqNSK0o6oimYAb80',
    appId: '1:550999966406:android:adfeb7cccbe77e52998dc7',
    messagingSenderId: '550999966406',
    projectId: 'flutter-tp2-groupe5',
    storageBucket: 'flutter-tp2-groupe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfo2-6M7tgfG6n1H9SX9iu70nAukR9guU',
    appId: '1:550999966406:ios:1c937b7eecdd6bf2998dc7',
    messagingSenderId: '550999966406',
    projectId: 'flutter-tp2-groupe5',
    storageBucket: 'flutter-tp2-groupe5.appspot.com',
    iosClientId: '550999966406-5biit240n8g5pfvl47fl697dqhdl1bg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfo2-6M7tgfG6n1H9SX9iu70nAukR9guU',
    appId: '1:550999966406:ios:cecb8da1496e65a7998dc7',
    messagingSenderId: '550999966406',
    projectId: 'flutter-tp2-groupe5',
    storageBucket: 'flutter-tp2-groupe5.appspot.com',
    iosClientId: '550999966406-cpgkb3kld82umevjco4927ka72i9jbgl.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2.RunnerTests',
  );
}
